spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/musicly
    username: postgres
    password: postgres
  devtools:
    add-properties: true

server:
  port: 8080

management:
  endpoint:
    web:
      exposure:
        include: '*'
